### ISSUE TITLE
Cannot browse into a folder shared with a guest user

### ISSUE THREAD

**Issue by davitol** [owncloud/guests#124] opened 2017-07-21 10:56 UTC
Using https://github.com/owncloud/guests/pull/109 PR

**Steps to reproduce**

1. Create a guest user sharing a folder that contains files
2. Log in with the guest account and try to access inside the shared folder

**Expected behavior**

The files should be shown

**Current behavior**

Cannot access to the files of the folder

```
{"reqId":"xnN0SONaTi7Rcbi1Pz2E","level":2,"time":"2017-07-21T10:49:01+00:00","remoteAddr":"85.57.168.79","user":"dtc_mymail@hotmail.com","app":"filesystem","method":"GET","url":"\/index.php\/avatar\/dtc_mymail%40hotmail.com\/28","message":"Storage wrapper 'oc_readonly' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems."}
{"reqId":"aWs3HRnyjEQ9qxqiPj7T","level":2,"time":"2017-07-21T10:49:01+00:00","remoteAddr":"85.57.168.79","user":"dtc_mymail@hotmail.com","app":"filesystem","method":"PROPFIND","url":"\/remote.php\/dav\/files\/dtc_mymail%40hotmail.com\/remote.php\/dav\/files\/dtc_mymail%40hotmail.com\/PleaseWork","message":"Storage wrapper 'oc_readonly' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems."}
{"reqId":"iNfnPvKGxbKghdXt8Xf6","level":2,"time":"2017-07-21T10:49:01+00:00","remoteAddr":"85.57.168.79","user":"dtc_mymail@hotmail.com","app":"filesystem","method":"PROPFIND","url":"\/remote.php\/dav\/files\/dtc_mymail%40hotmail.com\/","message":"Storage wrapper 'oc_readonly' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems."}
{"reqId":"mn87zh4pQQRaHV5Op7YL","level":2,"time":"2017-07-21T10:49:01+00:00","remoteAddr":"85.57.168.79","user":"dtc_mymail@hotmail.com","app":"filesystem","method":"GET","url":"\/index.php\/avatar\/dtc_mymail%40hotmail.com\/28","message":"Storage wrapper 'oc_readonly' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems."}
{"reqId":"0IUNKuglXNjWRSOOx54A","level":2,"time":"2017-07-21T10:49:02+00:00","remoteAddr":"85.57.168.79","user":"dtc_mymail@hotmail.com","app":"filesystem","method":"GET","url":"\/index.php\/apps\/files\/ajax\/getstoragestats.php?dir=%2F","message":"Storage wrapper 'oc_readonly' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems."}
{"reqId":"ivfTYBWnKWOP0nguaDrV","level":2,"time":"2017-07-21T10:49:38+00:00","remoteAddr":"85.57.168.79","user":"dtc_mymail@hotmail.com","app":"filesystem","method":"GET","url":"\/index.php\/apps\/files\/ajax\/getstoragestats.php?dir=%2F","message":"Storage wrapper 'oc_readonly' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems."}
```

@pmaier1 @cortho FYI

**Comment by cortho** [comment] 2017-07-21 11:11
I cannot confirm this. Is there some additional info/logs?

**Comment by davitol** [comment] 2017-07-21 11:26
Retested in a fresh container with the PR and I cannot reproduce it on this new server. So i'll try to investigate what happened in the other configuration.

**Comment by cortho** [comment] 2017-08-18 09:26
Very likely this was caused by https://github.com/owncloud/core/issues/28730 which was fixed with https://github.com/owncloud/core/pull/28732 -> closing

**Closed by cortho** 2017-08-18 09:26 UTC
Labels: bug, sev3-medium
