### ISSUE TITLE
Guest Users can not delete file

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/guests#134] opened 2017-08-15 09:54 UTC
As a guest user (with the permissions to do so), I want to delete a file. 
Deletion is not possible, just an error message is shown

Permissions are correctly set:
![image](https://user-images.githubusercontent.com/6403243/29311009-589281f0-81b0-11e7-899d-b5d418c846b8.png)

### steps to reproduce
1) share a folder with a guest user
2) login as guest user
3) delete something
  - upload a new file and delete it
  - try to delete an existing file

### expected behavior
I can delete the file

### actual behavior
Error message `Error deleting file "Add as guests.png" is show ` and no file is deleted
![image](https://user-images.githubusercontent.com/6403243/29311019-6c354670-81b0-11e7-997a-698e760b7268.png)

### relevant log entry
```
{
  "level": 3, 
  "url": "/owncloud/remote.php/webdav/Photos/Add%20as%20guests.png", 
  "app": "remote", 
  "method": "DELETE", 
  "reqId": "EOFsExkuOtnw2Ni6GTZv", 
  "user": "pjahns_owncloud_com", 
  "time": "2017-08-15T09:48:27+00:00", 
  "message": "Exception: {
"Exception":"Error",
"Message":"Call to a member function getStorageId() on array",
"Code":0,"Trace":"
#0 /var/www/owncloud/lib/private/Files/Cache/Wrapper/CacheWrapper.php(67): OC\Files\Cache\Wrapper\ReadOnlyCachePermissionsMask->formatCacheEntry(Array\)
#1 /var/www/owncloud/lib/private/Files/Cache/Scanner.php(176): OC\Files\Cache\Wrapper\CacheWrapper->get('files_trashbin'\)
#2 /var/www/owncloud/lib/private/Files/Cache/Scanner.php(168): OC\Files\Cache\Scanner->scanFile('files_trashbin'\)
#3 /var/www/owncloud/lib/private/Files/Cache/Scanner.php(309): OC\Files\Cache\Scanner->scanFile('files_trashbin/...', 3, -1, NULL, false\)
#4 /var/www/owncloud/lib/private/Files/Cache/Updater.php(124): OC\Files\Cache\Scanner->scan('files_trashbin/...', false, 3, false\)
#5 /var/www/owncloud/lib/private/Files/View.php(314): OC\Files\Cache\Updater->update('files_trashbin/...', 1502790507\)
#6 /var/www/owncloud/lib/private/Files/View.php(1138): OC\Files\View->writeUpdate(Object(OCA\Files_Trashbin\Storage), 'files_trashbin/...'\)
#7 /var/www/owncloud/lib/private/Files/View.php(262): OC\Files\View->basicOperation('mkdir', '/files_trashbin...', Array\)
#8 /var/www/owncloud/apps/files_trashbin/lib/Trashbin.php(153): OC\Files\View->mkdir('files_trashbin/...'\)
#9 /var/www/owncloud/apps/files_trashbin/lib/Trashbin.php(250): OCA\Files_Trashbin\Trashbin::setUpTrash('pjahns_owncloud...'\)
#10 /var/www/owncloud/apps/files_trashbin/lib/Storage.php(185): OCA\Files_Trashbin\Trashbin::move2trash('Photos/Add as g...'\)
#11 /var/www/owncloud/apps/files_trashbin/lib/Storage.php(120): OCA\Files_Trashbin\Storage->doDelete('Add as guests.p...', 'unlink'\)
#12 /var/www/owncloud/lib/private/Files/View.php(1123): OCA\Files_Trashbin\Storage->unlink('Add as guests.p...'\)
#13 /var/www/owncloud/lib/private/Files/View.php(693): OC\Files\View->basicOperation('unlink', '/Photos/Add as ...', Array\)
#14 /var/www/owncloud/apps/dav/lib/Connector/Sabre/File.php(346): OC\Files\View->unlink('/Photos/Add as ...'\)
#15 /var/www/owncloud/lib/composer/sabre/dav/lib/DAV/Tree.php(179): OCA\DAV\Connector\Sabre\File->delete(\)
#16 /var/www/owncloud/lib/composer/sabre/dav/lib/DAV/CorePlugin.php(287): Sabre\DAV\Tree->delete('Photos/Add as g...'\)
#17 [internal function]: Sabre\DAV\CorePlugin->httpDelete(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response)\)
#18 /var/www/owncloud/lib/composer/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array\)
#19 /var/www/owncloud/lib/composer/sabre/dav/lib/DAV/Server.php(479): Sabre\Event\EventEmitter->emit('method:DELETE', Array\)
#20 /var/www/owncloud/lib/composer/sabre/dav/lib/DAV/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response)\)
#21 /var/www/owncloud/apps/dav/appinfo/v1/webdav.php(63): Sabre\DAV\Server->exec(\)
#22 /var/www/owncloud/remote.php(165): require_once('/var/www/ownclo...'\)
#23 {main}",
"File":"/var/www/owncloud/lib/private/Files/Cache/Wrapper/ReadOnlyCachePermissionsMask.php",
"Line":54}", 
  "remoteAddr": "172.17.0.1"
}
```

**Comment by pmaier1** [comment] 2017-08-15 10:08
Mhh, thanks for reporting!
@cortho maybe?

**Comment by cortho** [comment] 2017-08-16 08:03
Yes, I'll assign this, when the new registration PR is finished.

**Comment by cortho** [comment] 2017-08-16 11:41
Info: This happens when and because the files_trashbin folder is not present in the guest user's data directory, could be a files_trashbin issue

**Comment by PVince81** [comment] 2017-08-16 11:55
Duplicate of https://github.com/owncloud/guests/issues/31

**Closed by PVince81** 2017-08-16 11:55 UTC
Labels: bug, p2-high, sev3-medium
