### ISSUE TITLE
Sharing using email with uppercase letters in TLD

### ISSUE THREAD

**Issue by KuenzelIT** [owncloud/guests#222] opened 2018-06-20 09:46 UTC
Hi,

if I share some file with someone using an uppercase letter in the TLD, e.g. contact@ExAmPle.org, then I can't notify this guest by email. The request fails with a 500 internal server error. I get the following error in my log file:

{"reqId":"WyoeiDjZKKiyFA6xyN1W0gAAAA0","level":3,"time":"2018-06-20T09:29:45+00:00","remoteAddr":"141.21.73.17","user":"me@exmaple.org","app":"index","method":"POST","url":"\/index.php\/core\/ajax\/share.php","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\InvalidParameterException\",\"Message\":\"Parameter \\\"fileId\\\" for route \\\"files.viewcontroller.showFile\\\" must match \\\"[^\\\/]++\\\" (\\\"\\\" given) to generate a corresponding URL.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php(119): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->doGenerate(Array, Array, Array, Array, Array, 'files.viewcontr...', 1, Array, Array)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(382): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('files.viewcontr...', Array, 1)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/CachingRouter.php(60): OC\\\\Route\\\\Router->generate('files.viewcontr...', Array, false)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/URLGenerator.php(77): OC\\\\Route\\\\CachingRouter->generate('files.viewcontr...', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/URLGenerator.php(90): OC\\\\URLGenerator->linkToRoute('files.viewcontr...', Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Share\\\/MailNotifications.php(143): OC\\\\URLGenerator->linkToRouteAbsolute('files.viewcontr...', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/core\\\/ajax\\\/share.php(134): OC\\\\Share\\\\MailNotifications->sendInternalShareMail(Array, '47893', 'file')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Route.php(155): require_once('\\\/var\\\/www\\\/ownclo...')\\n#8 [internal function]: OC\\\\Route\\\\Route->OC\\\\Route\\\\{closure}(NULL)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): call_user_func(Object(Closure), Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(912): OC\\\\Route\\\\Router->match('\\\/core\\\/ajax\\\/shar...')\\n#11 \\\/var\\\/www\\\/owncloud\\\/index.php(55): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":146}"}

Everything works fine with lowercase guest mails. Is this an already known bug?

Thanks!

**Comment by PVince81** [comment] 2018-06-20 09:58
Strange, the error you see seems to be related to the fileid likely being undefined, as if the sharing entity wouldn't exist. But maybe this is just a side-effect of the actual issue.

**Comment by PVince81** [comment] 2018-06-20 10:01
I can't reproduce this issue, I've used my local email address and mixed casing in the TLD.

This is with 10.0.9RC1.

@KuenzelIT please specify details, OC version, guest app version. If possible try again with latest versions.

**Comment by KuenzelIT** [comment] 2018-06-20 10:27
OC-Version: 10.0.8
Guests-App: 0.5.0

As far as I know there are no newer stable versions available.

Are there any other details that could be helpful?

**Comment by PVince81** [comment] 2018-06-20 10:31
please also post details about what modes you used when configuring the email server (SMTP, sendmail or other) in ownCloud's settings pages

**Comment by KuenzelIT** [comment] 2018-06-27 12:47
Sorry for the late response.

The smtpmode is set to "php". Did you mean this one?
```
'mail_smtpmode' => 'php',
```

**Comment by KuenzelIT** [comment] 2018-07-17 11:19
Is there anything else I can try?

**Comment by KuenzelIT** [comment] 2018-08-01 11:40
Or any other details I can provide to find a solution?

**Comment by PVince81** [comment] 2018-08-08 14:25
not reproducible either locally with "php" smtp mode

the error you got up there doesn't look related to the email address at all

did you test sharing the exact same file with two different casings ? it more looks like the file itself is broken in some way as it seems to have trouble with its file id.

Please try creating a brand new file in the root folder of the current user, then share with an email with lower case domain, then upper case domain. For a brand new file I expect that sharing will work in both.

**Comment by KuenzelIT** [comment] 2018-08-20 09:28
Hi again,

sorry for the late response again.

I did as you told me to do:  I created a new textfile and shared it with non existing guests. If I share it with `test@example.de` everything works fine. If I share it with `test2@ExAmPle.DE` the sharing works but no mail is sent and the "notify by email" button isn't working either (it is loading forever). If I then share again with `test2@ExAmPle.DE` it also works with the emails, since it uses the existing guest user.

This is what I get in the logs when sharing:

```
{"reqId":"W3qIwBgNJ1J-75-FCUp@2gAAABE","level":3,"time":"2018-08-20T09:24:16+00:00","remoteAddr":"141.21.17.13","user":"kuenzel@example.de","app":"no app in context","method":"PUT","url":"\/index.php\/apps\/guests\/users","message":"User backend OC\\User\\Database is returning home: \/mnt\/data\/cloud_files\/test@example.de for user: test@example.de which differs from existing value: "}
```

And this if I try to send the notification mail:

```
{"reqId":"W3qIyFZNNJ9iY8pq1JdXXAAAAAM","level":3,"time":"2018-08-20T09:24:24+00:00","remoteAddr":"141.21.17.13","user":"kuenzel@example.de","app":"PHP","method":"POST","url":"\/index.php\/core\/ajax\/share.php","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/Share\/MailNotifications.php#136"}
{"reqId":"W3qIyFZNNJ9iY8pq1JdXXAAAAAM","level":3,"time":"2018-08-20T09:24:24+00:00","remoteAddr":"141.21.17.13","user":"kuenzel@example.de","app":"PHP","method":"POST","url":"\/index.php\/core\/ajax\/share.php","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/Share\/MailNotifications.php#149"}
{"reqId":"W3qIyFZNNJ9iY8pq1JdXXAAAAAM","level":3,"time":"2018-08-20T09:24:24+00:00","remoteAddr":"141.21.17.13","user":"kuenzel@example.de","app":"index","method":"POST","url":"\/index.php\/core\/ajax\/share.php","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\InvalidParameterException\",\"Message\":\"Parameter \\\"fileId\\\" for route \\\"files.viewcontroller.showFile\\\" must match \\\"[^\\\/]++\\\" (\\\"\\\" given) to generate a corresponding URL.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php(119): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->doGenerate(Array, Array, Array, Array, Array, 'files.viewcontr...', 1, Array, Array)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(382): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('files.viewcontr...', Array, 1)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/CachingRouter.php(60): OC\\\\Route\\\\Router->generate('files.viewcontr...', Array, false)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/URLGenerator.php(77): OC\\\\Route\\\\CachingRouter->generate('files.viewcontr...', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/URLGenerator.php(90): OC\\\\URLGenerator->linkToRoute('files.viewcontr...', Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Share\\\/MailNotifications.php(149): OC\\\\URLGenerator->linkToRouteAbsolute('files.viewcontr...', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/core\\\/ajax\\\/share.php(135): OC\\\\Share\\\\MailNotifications->sendInternalShareMail(Array, '78085', 'file')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Route.php(155): require_once('\\\/var\\\/www\\\/ownclo...')\\n#8 [internal function]: OC\\\\Route\\\\Route->OC\\\\Route\\\\{closure}(NULL)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): call_user_func(Object(Closure), Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(919): OC\\\\Route\\\\Router->match('\\\/core\\\/ajax\\\/shar...')\\n#11 \\\/var\\\/www\\\/owncloud\\\/index.php(55): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":146}"}
```

Thanks for your help!

**Comment by PVince81** [comment] 2018-08-23 11:55
are you using an official 10.0.8 build ?

the lines the errors point to don't seem to match the error message:
- https://github.com/owncloud/core/blob/v10.0.8/lib/private/Share/MailNotifications.php#L136
- https://github.com/owncloud/core/blob/v10.0.8/lib/private/Share/MailNotifications.php#L149

there should be an array visible on the lines in question for the error to make sense

something seems to be happening there on your setup that might indirectly prevent the file id to be found.

mind using the issue template and providing signing status ? see https://raw.githubusercontent.com/owncloud/core/master/.github/issue_template.md

**Comment by jenson2k** [comment] 2018-12-04 15:21
We have the same problem. Mail adresses with uppercase letters wont be informed about a newly created account or a new share notification.

oC Version: 10.0.10.4
Guest App version: 0.7.0

`{"reqId":"a5GfSGQFRuGDkwWytmfd","level":3,"time":"2018-12-04T16:15:47+01:00","remoteAddr":"10.90.1.46","user":"3C30A33F-0C39-44D0-91FD-BEAA7EC0227C","app":"PHP","method":"POST","url":"\/index.php\/core\/ajax\/share.php","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/Share\/MailNotifications.php#142"}
{"reqId":"a5GfSGQFRuGDkwWytmfd","level":3,"time":"2018-12-04T16:15:47+01:00","remoteAddr":"10.90.1.46","user":"3C30A33F-0C39-44D0-91FD-BEAA7EC0227C","app":"PHP","method":"POST","url":"\/index.php\/core\/ajax\/share.php","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/Share\/MailNotifications.php#155"}
{"reqId":"a5GfSGQFRuGDkwWytmfd","level":3,"time":"2018-12-04T16:15:47+01:00","remoteAddr":"10.90.1.46","user":"3C30A33F-0C39-44D0-91FD-BEAA7EC0227C","app":"index","method":"POST","url":"\/index.php\/core\/ajax\/share.php","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\InvalidParameterException\",\"Message\":\"Parameter \\\"fileId\\\" for route \\\"files.viewcontroller.showFile\\\" must match \\\"[^\\\/]++\\\" (\\\"\\\" given) to generate a corresponding URL.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php(119): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->doGenerate(Array, Array, Array, Array, Array, 'files.viewcontr...', 1, Array, Array)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(382): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('files.viewcontr...', Array, 1)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/CachingRouter.php(60): OC\\\\Route\\\\Router->generate('files.viewcontr...', Array, false)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/URLGenerator.php(86): OC\\\\Route\\\\CachingRouter->generate('files.viewcontr...', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/URLGenerator.php(99): OC\\\\URLGenerator->linkToRoute('files.viewcontr...', Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Share\\\/MailNotifications.php(155): OC\\\\URLGenerator->linkToRouteAbsolute('files.viewcontr...', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/core\\\/ajax\\\/share.php(136): OC\\\\Share\\\\MailNotifications->sendInternalShareMail(Array, '35109', 'folder')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Route.php(155): require_once('\\\/var\\\/www\\\/ownclo...')\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): OC\\\\Route\\\\Route->OC\\\\Route\\\\{closure}(NULL)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(909): OC\\\\Route\\\\Router->match('\\\/core\\\/ajax\\\/shar...')\\n#10 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":146}"}`

**Comment by HariBhandari07** [comment] 2019-06-04 03:57
This issue is fixed in https://github.com/owncloud/core/pull/35084

**Comment by individual-it** [comment] 2019-06-04 04:04
test were added in  #328 
closing for now, feel free to open again if the problem persists

**Closed** 2019-06-04 05:20 UTC
