### ISSUE TITLE
Guests users can log into ownCloud after disabling the app

### ISSUE THREAD

**Issue by davitol** [owncloud/guests#123] opened 2017-07-20 13:23 UTC
Guests users can log into ownCloud after disabling the app

**Steps to reproduce**
1. Add a guest user via shareTabView
2. Log in/out the guest account
3. Disable guests app via ```occ app:disable guests``` command
4. Log in guest account

**Expected behavior**
Guest user is no longer available

**Current behavior**
Guest user is still able to log into ownCloud

@cortho @pmaier1

**Comment by cortho** [comment] 2017-07-21 11:58
Looks like this scenario has not been considered until now.

For expected behavior _Guest user is no longer available_, it would be possible to disable all guest users, but there are more questions: What would happen to their shares? Will disabled guests be enabled again, when the guests app is re-enabled? 

Another expected behavior could be, that disabling the app only means that no new guest users can be created, but existing still can use their shares.

So the basic question for this issue should be: What should happen, when the app is disabled.

**Comment by pmaier1** [comment] 2017-07-24 13:43
> Looks like this scenario has not been considered until now.

True :)

> Another expected behavior could be, that disabling the app only means that no new guest users can be created, but existing still can use their shares.

This would be my preference. Guest accounts are disabled by removing shares or by a conscious (and scriptable) disable by an admin. Enabling/disabling the app adds/removes the ability to invite new guests.

**Comment by PVince81** [comment] 2017-09-04 09:05
In this case this ticket is a won't fix. Disabling the app would only disallow the creation of new guests by regular users. Existing guests would still exist.

**Closed** 2017-09-04 09:05 UTC
Labels: bug, question, sev2-high
